"""empty message

Revision ID: 91c2abd0b178
Revises: aa81b3c0f11e
Create Date: 2024-04-29 17:18:26.590847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91c2abd0b178'
down_revision = 'aa81b3c0f11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('name')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=36), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=110),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=110),
               existing_nullable=True)
        batch_op.drop_column('image')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    # ### end Alembic commands ###
